name: Build and Push Docker Image

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main, dev ]
    paths-ignore:
      - 'README.md'
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/m324-chat-app
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=C:\actions-runner\.buildx-cache
          cache-to: type=local,dest=C:\actions-runner\.buildx-cache,mode=max

